env vars validation added

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,9 +9,9 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     environment: production
-    env:
-      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
-      VITE_API_BASE_PATH: ${{ secrets.VITE_API_BASE_PATH }}
+      env:
+        VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
+        VITE_API_BASE_PATH: ${{ vars.VITE_API_BASE_PATH }}
 
     steps:
       # ✅ Pull repo
@@ -23,6 +23,19 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 20
+
+      # ✅ Validate env
+      - name: Validate env
+        run: |
+          if [ -z "$VITE_API_BASE_URL" ]; then
+            echo "VITE_API_BASE_URL is missing!"
+            exit 1
+          fi
+
+          if [ -z "$VITE_API_BASE_PATH" ]; then
+            echo "VITE_API_BASE_PATH is missing!"
+            exit 1
+          fi
 
       # ✅ Faster installs
       - name: Install dependencies
